import './globals.css'
import type { Metadata } from 'next'
import {
	Roboto_Condensed,
	Cormorant_Garamond,
	Dancing_Script,
} from 'next/font/google'
import DesktopNav from '@/components/Navigation/DesktopNav'
import MobileNav from '@/components/Navigation/MobileNav'
import Navigation from './Navigation'

const roboto_condensed = Roboto_Condensed({
	subsets: ['latin'],
	display: 'swap',
	weight: '300',
	variable: '--font-roboto-condensed',
})

const cormorant_garmond = Cormorant_Garamond({
	subsets: ['latin'],
	display: 'swap',
	weight: '700',
	variable: '--font-cormorant-garmond',
})
const dancing_script = Dancing_Script({
	subsets: ['latin'],
	display: 'swap',
	weight: '400',
	variable: '--font-dancing-script',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html
			lang='en'
			className={`${roboto_condensed.variable} ${dancing_script.variable} ${cormorant_garmond.variable}`}>
			<body className='font-roboto overflow-hidden max-w-full'>
				<Navigation />
				{children}
			</body>
		</html>
	)
}
